language: node_js

node_js:
  - "10"

branches:
  only:
    - lab
    - staging
    - prod

cache: yarn

install:
  - yarn

before_script: chmod -R +x scripts

script:
  - ./scripts/test.sh
  - ./scripts/build.sh

deploy:
  provider: "s3"
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: "${AWS_S3_BUCKET}"
  local_dir: "dist"
  skip_cleanup: true
  on:
    branch:
      - lab
      - staging
      - prod
