language: node_js

node_js:
  - "10"

branches:
  only:
    - lab
    - staging
    - master

cache: yarn

install:
  - yarn

before_script:
  - yarn lint

script:
  - |
    if [ $TRAVIS_BRANCH == "lab" ]; then
       yarn build:lab
    elif [ $TRAVIS_BRANCH == "staging" ]; then
       yarn build:staging
    elif [ $TRAVIS_BRANCH == "master" ]; then
       yarn build:prod
    fi
deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
  bucket: ${AWS_S3_BUCKET}
  local_dir: "dist"
  skip_cleanup: true
  on:
    branch:
      - master
      - lab
      - staging
