language: node_js

node_js: 
  - "10"

branches:
  only:
    - master
    - staging
    - prod

cache: yarn

install:
  - npm install

jobs: 
  include:
    - stage: test
      name: test
      if: |
        branch =~ /(master|staging|prod)/ AND \
        type = pull_request
      script: 
        - "yarn lint"
    - stage: deploy
      name: deploy
      if: |
        branch =~ /(staging|prod)/ AND \
        type = push
      script: 
        - "yarn build:${$TRAVIS_BRANCH}"
      deploy:
        provider: "s3"
        access_key_id: "${AWS_ACCESS_KEY}"
        secret_access_key: "${AWS_SECRET_KEY}"
        bucket: "${AWS_S3_BUCKET}"
        local_dir: "dist"
        skip_cleanup: true        
        on: 
          branch: 
            - staging
            - prod